$siteRoot = Split-Path -Parent $PSScriptRoot
$imagesRoot = Join-Path $siteRoot "images"
$extensions = ".avif", ".gif", ".jpeg", ".jpg", ".png", ".webp"
$galleries = [ordered]@{}

Get-ChildItem -LiteralPath $imagesRoot -Directory | Sort-Object Name | ForEach-Object {
    $folder = $_
    $images = Get-ChildItem -LiteralPath $folder.FullName -File |
        Where-Object { $extensions -contains $_.Extension.ToLowerInvariant() } |
        Sort-Object Name |
        ForEach-Object { "images/$($folder.Name)/$($_.Name)" }

    $galleries[$folder.Name] = @($images)
}

$json = $galleries | ConvertTo-Json -Depth 3
$output = "/* Generated by scripts/generate-galleries.ps1. */`nwindow.projectGalleries = $json;`n"
Set-Content -LiteralPath (Join-Path $siteRoot "gallery-manifest.js") -Value $output -NoNewline

Write-Host "Generated galleries for $($galleries.Count) project folders."
